version: '3'
services:
  bert-toxic:
    image: "crawftv/tf_serving_bert_toxic:1556822021_v5"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "800M"
        reservations:
          cpus: "0.25"
          memory: "100M"
    ports:
      - "8500:8500"
      - "8501:8501"
    labels:
      kompose.service.type: LoadBalancer
  toxic-client:
    image: "crawftv/bert_toxic_client:v5"
    ports:
      - "5000:5000"
    depends_on:
      - bert-toxic
    labels:
      kompose.service.type: LoadBalancer
